### ISSUE TITLE
Fungal CorpseObject does not exist

### ISSUE THREAD

**Issue by MrHrulgin** [Kizby/Limber#4]
With the Deep Jungle release, Limber won't load.

=== Limber 0.2.5-alpha Errors ===
<...>\steamapps\workshop\content\333640\2275906495\FungusCorpse.cs(15,17): error CS0103: The name 'CorpseObject' does not exist in the current context
<...>\steamapps\workshop\content\333640\2275906495\FungusCorpse.cs(16,17): error CS0103: The name 'CorpseObject' does not exist in the current context
== Warnings ==
None

**Comment by Kizby** [comment]
Thanks for the heads up! Fixed at 76db4236cc957c7bb599cb21234c8ab18e11ce9b
